# COMMON
GAME_NAME = 'Snake-labirinth'

# VIDEO
DEFAULT_RESOLUTION = (640, 480)

# SNAKE BLOCK
DEFAULT_BLOCK_SIZE = 40


# GAME FIELD

DEFAULT_CELL_SIZE = DEFAULT_BLOCK_SIZE
DEFAULT_FIELD_DIMENSIONS = (480, 480)
DEFAULT_SIZE = DEFAULT_BLOCK_SIZE
BLOCK_SIZE = DEFAULT_BLOCK_SIZE
BLOCK_WIDTH = BLOCK_SIZE
BLOCK_HEIGHT = BLOCK_SIZE

STARTUP_X = DEFAULT_RESOLUTION[0]/2
STARTUP_Y = DEFAULT_RESOLUTION[1]/2


# COLORS

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)

class SYMBOLS:
    __slots__ = ()
